# Generated by Django 3.2.7 on 2021-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edinet', '0004_alter_prestation_archiv_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='P_LRE',
            field=models.IntegerField(null=True),
        ),
    ]
