# Generated by Django 3.2.7 on 2021-10-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edinet', '0005_alter_prestation_p_lre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='APCL',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='APNB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='LIASSE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='PPCL',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='PPNB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='P_AVIS',
            field=models.IntegerField(null=True),
        ),
    ]
